{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "97ba0860-5624-4e52-ad93-148fe65e48ba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🧹 limpieza realizada\n",
      "✅ navegador iniciado\n",
      "📄 procesando página 1\n",
      "📄 procesando página 2\n",
      "📄 procesando página 3\n",
      "📄 procesando página 4\n",
      "📄 procesando página 5\n",
      "📄 procesando página 6\n",
      "📄 procesando página 7\n",
      "📄 procesando página 8\n",
      "📄 procesando página 9\n",
      "✅ autos extraidos: 270\n",
      "\n",
      "🔍 primeros 5 resultados:\n",
      "{'marca': 'toyota', 'modelo': 'hilux dcab 4x4 2.8 aut', 'year': '2020', 'kilometraje': '100000 km', 'combustible': 'diesel', 'ciudad': 'villarrica', 'url': 'https://www.yapo.cl/autos-usados/toyota-hilux-srv-automatica-4x4-2020/32249039', 'precio': 21990000, 'fecha_captura': '2026-04-28 16:54:11', 'grupo': 'autotec', 'usuario': 'dani'}\n",
      "{'marca': 'chevrolet', 'modelo': 'tracker', 'year': '2020', 'kilometraje': '48087 km', 'combustible': 'bencina', 'ciudad': 'valparaíso', 'url': 'https://www.yapo.cl/autos-usados/chevrolet-tracker-1-8-lt-mt-2020/31206199', 'precio': 10490000, 'fecha_captura': '2026-04-28 16:54:12', 'grupo': 'autotec', 'usuario': 'dani'}\n",
      "{'marca': 'chevrolet', 'modelo': 'spin', 'year': '2018', 'kilometraje': '174000 km', 'combustible': 'bencina', 'ciudad': 'valparaíso', 'url': 'https://www.yapo.cl/autos-usados/chevrolet-spin-spin-1-8-2018/31959269', 'precio': 7590000, 'fecha_captura': '2026-04-28 16:54:12', 'grupo': 'autotec', 'usuario': 'dani'}\n",
      "{'marca': 'bmw', 'modelo': 'x1', 'year': '2019', 'kilometraje': '119943 km', 'combustible': 'diesel', 'ciudad': 'las condes', 'url': 'https://www.yapo.cl/autos-usados/bmw-x1-sdrive-18d-2-0-aut-2019/32184812', 'precio': 17900000, 'fecha_captura': '2026-04-28 16:54:12', 'grupo': 'autotec', 'usuario': 'dani'}\n",
      "{'marca': 'bmw', 'modelo': '220i', 'year': '2017', 'kilometraje': '87199 km', 'combustible': 'bencina', 'ciudad': 'las condes', 'url': 'https://www.yapo.cl/autos-usados/bmw-220i-coupe-2-0-aut-2017/32184814', 'precio': 18900000, 'fecha_captura': '2026-04-28 16:54:12', 'grupo': 'autotec', 'usuario': 'dani'}\n"
     ]
    }
   ],
   "source": [
    "def ejecutar_extraccion():\n",
    "\n",
    "    import os\n",
    "    import time\n",
    "    import re\n",
    "    from selenium import webdriver\n",
    "    from selenium.webdriver.chrome.options import Options\n",
    "    from selenium.webdriver.common.by import By\n",
    "    from selenium.webdriver.support.ui import WebDriverWait\n",
    "    from selenium.webdriver.support import expected_conditions as EC\n",
    "\n",
    "    # --- LIMPIEZA ---\n",
    "    os.system(\"pkill -9 chrome\")\n",
    "    os.system(\"pkill -9 chromedriver\")\n",
    "    os.system(\"rm -rf /tmp/.com.google.Chrome.*\")\n",
    "    os.system(\"rm -rf /tmp/.org.chromium.Chromium.*\")\n",
    "\n",
    "    print(\"🧹 limpieza realizada\")\n",
    "\n",
    "    lista_autos = []\n",
    "    driver = None\n",
    "\n",
    "    NOMBRE_GRUPO = \"autotec\"\n",
    "    USUARIO = \"dani\"\n",
    "\n",
    "    # --- NAVEGADOR ---\n",
    "    options = Options()\n",
    "    options.binary_location = \"/usr/bin/google-chrome\"\n",
    "    options.add_argument(\"--no-sandbox\")\n",
    "    options.add_argument(\"--disable-dev-shm-usage\")\n",
    "    options.add_argument(\"--disable-gpu\")\n",
    "    options.add_argument(\"--window-size=1920,1080\")\n",
    "    options.add_argument(\"--headless=new\")\n",
    "\n",
    "    try:\n",
    "        driver = webdriver.Chrome(options=options)\n",
    "        print(\"✅ navegador iniciado\")\n",
    "\n",
    "        for pagina in range(18):\n",
    "\n",
    "            url = \"https://www.yapo.cl/autos-usados\" if pagina == 0 else f\"https://www.yapo.cl/autos-usados.{pagina + 1}\"\n",
    "            driver.get(url)\n",
    "\n",
    "            print(f\"📄 procesando página {pagina + 1}\")\n",
    "            time.sleep(8)\n",
    "\n",
    "            bloques = WebDriverWait(driver, 20).until(\n",
    "                EC.presence_of_all_elements_located(\n",
    "                    (By.CSS_SELECTOR, \"a.d3-ad-tile__description\")\n",
    "                )\n",
    "            )\n",
    "\n",
    "            for bloque in bloques:\n",
    "                try:\n",
    "                    nombre = bloque.find_element(\n",
    "                        By.CSS_SELECTOR, \"span.d3-ad-tile__title\"\n",
    "                    ).text.lower().strip()\n",
    "\n",
    "                    partes = nombre.split()\n",
    "                    marca = partes[0] if len(partes) > 0 else \"\"\n",
    "                    modelo = \" \".join(partes[1:]) if len(partes) > 1 else \"\"\n",
    "\n",
    "                    # --- precio ---\n",
    "                    try:\n",
    "                        precio_elemento = bloque.find_element(\n",
    "                            By.CSS_SELECTOR, \"div.d3-ad-tile__price\"\n",
    "                        )\n",
    "\n",
    "                        precio_texto = driver.execute_script(\n",
    "                            \"return arguments[0].childNodes[0].textContent;\",\n",
    "                            precio_elemento\n",
    "                        ).strip()\n",
    "\n",
    "                    except:\n",
    "                        precio_texto = \"\"\n",
    "\n",
    "                    numeros = re.findall(r\"\\d+\", precio_texto)\n",
    "                    precio = int(\"\".join(numeros)) if numeros else None\n",
    "\n",
    "                    # --- ciudad ---\n",
    "                    try:\n",
    "                        ciudad = bloque.find_element(\n",
    "                            By.CSS_SELECTOR, \"div.d3-ad-tile__location\"\n",
    "                        ).text.lower().strip()\n",
    "                    except:\n",
    "                        ciudad = \"\"\n",
    "\n",
    "                    # --- url ---\n",
    "                    url_auto = bloque.get_attribute(\"href\")\n",
    "\n",
    "                    # --- detalles ---\n",
    "                    detalles = bloque.find_elements(\n",
    "                        By.CSS_SELECTOR, \"li.d3-ad-tile__details-item\"\n",
    "                    )\n",
    "\n",
    "                    year = \"\"\n",
    "                    kilometraje = \"\"\n",
    "                    combustible = \"\"\n",
    "\n",
    "                    for d in detalles:\n",
    "                        texto = d.text.lower().strip()\n",
    "\n",
    "                        if texto.isdigit() and len(texto) == 4:\n",
    "                            year = texto\n",
    "                        elif \"km\" in texto:\n",
    "                            kilometraje = texto\n",
    "                        elif texto in [\n",
    "                            \"bencina\", \"diesel\", \"diésel\",\n",
    "                            \"hibrido\", \"híbrido\",\n",
    "                            \"electrico\", \"eléctrico\"\n",
    "                        ]:\n",
    "                            combustible = texto\n",
    "\n",
    "                    lista_autos.append({\n",
    "                        \"marca\": marca,\n",
    "                        \"modelo\": modelo,\n",
    "                        \"year\": year,\n",
    "                        \"kilometraje\": kilometraje,\n",
    "                        \"combustible\": combustible,\n",
    "                        \"ciudad\": ciudad,\n",
    "                        \"url\": url_auto,\n",
    "                        \"precio\": precio,\n",
    "                        \"fecha_captura\": time.strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
    "                        \"grupo\": NOMBRE_GRUPO,\n",
    "                        \"usuario\": USUARIO\n",
    "                    })\n",
    "\n",
    "                except Exception as e:\n",
    "                    print(\"⚠️ error:\", e)\n",
    "                    continue\n",
    "\n",
    "        print(f\"✅ autos extraidos: {len(lista_autos)}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(\"❌ error selenium:\", e)\n",
    "\n",
    "    finally:\n",
    "        if driver:\n",
    "            driver.quit()\n",
    "\n",
    "    return lista_autos\n",
    "\n",
    "# --- EJECUTAR ---\n",
    "resultado = ejecutar_extraccion()\n",
    "\n",
    "print(\"\\n🔍 primeros 5 resultados:\")\n",
    "for auto in resultado[:5]:\n",
    "    print(auto)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "917d1eae-4b1d-4f43-a6be-0b1ff0f968a3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>marca</th>\n",
       "      <th>modelo</th>\n",
       "      <th>year</th>\n",
       "      <th>kilometraje</th>\n",
       "      <th>combustible</th>\n",
       "      <th>ciudad</th>\n",
       "      <th>url</th>\n",
       "      <th>precio</th>\n",
       "      <th>fecha_captura</th>\n",
       "      <th>grupo</th>\n",
       "      <th>usuario</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>toyota</td>\n",
       "      <td>hilux dcab 4x4 2.8 aut</td>\n",
       "      <td>2020</td>\n",
       "      <td>100000 km</td>\n",
       "      <td>diesel</td>\n",
       "      <td>villarrica</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/toyota-hilux-...</td>\n",
       "      <td>21990000</td>\n",
       "      <td>2026-04-28 16:54:11</td>\n",
       "      <td>autotec</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>chevrolet</td>\n",
       "      <td>tracker</td>\n",
       "      <td>2020</td>\n",
       "      <td>48087 km</td>\n",
       "      <td>bencina</td>\n",
       "      <td>valparaíso</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/chevrolet-tra...</td>\n",
       "      <td>10490000</td>\n",
       "      <td>2026-04-28 16:54:12</td>\n",
       "      <td>autotec</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>chevrolet</td>\n",
       "      <td>spin</td>\n",
       "      <td>2018</td>\n",
       "      <td>174000 km</td>\n",
       "      <td>bencina</td>\n",
       "      <td>valparaíso</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/chevrolet-spi...</td>\n",
       "      <td>7590000</td>\n",
       "      <td>2026-04-28 16:54:12</td>\n",
       "      <td>autotec</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>bmw</td>\n",
       "      <td>x1</td>\n",
       "      <td>2019</td>\n",
       "      <td>119943 km</td>\n",
       "      <td>diesel</td>\n",
       "      <td>las condes</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/bmw-x1-sdrive...</td>\n",
       "      <td>17900000</td>\n",
       "      <td>2026-04-28 16:54:12</td>\n",
       "      <td>autotec</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>bmw</td>\n",
       "      <td>220i</td>\n",
       "      <td>2017</td>\n",
       "      <td>87199 km</td>\n",
       "      <td>bencina</td>\n",
       "      <td>las condes</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/bmw-220i-coup...</td>\n",
       "      <td>18900000</td>\n",
       "      <td>2026-04-28 16:54:12</td>\n",
       "      <td>autotec</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       marca                  modelo  year kilometraje combustible  \\\n",
       "0     toyota  hilux dcab 4x4 2.8 aut  2020   100000 km      diesel   \n",
       "1  chevrolet                 tracker  2020    48087 km     bencina   \n",
       "2  chevrolet                    spin  2018   174000 km     bencina   \n",
       "3        bmw                      x1  2019   119943 km      diesel   \n",
       "4        bmw                    220i  2017    87199 km     bencina   \n",
       "\n",
       "       ciudad                                                url    precio  \\\n",
       "0  villarrica  https://www.yapo.cl/autos-usados/toyota-hilux-...  21990000   \n",
       "1  valparaíso  https://www.yapo.cl/autos-usados/chevrolet-tra...  10490000   \n",
       "2  valparaíso  https://www.yapo.cl/autos-usados/chevrolet-spi...   7590000   \n",
       "3  las condes  https://www.yapo.cl/autos-usados/bmw-x1-sdrive...  17900000   \n",
       "4  las condes  https://www.yapo.cl/autos-usados/bmw-220i-coup...  18900000   \n",
       "\n",
       "         fecha_captura    grupo usuario  \n",
       "0  2026-04-28 16:54:11  autotec    dani  \n",
       "1  2026-04-28 16:54:12  autotec    dani  \n",
       "2  2026-04-28 16:54:12  autotec    dani  \n",
       "3  2026-04-28 16:54:12  autotec    dani  \n",
       "4  2026-04-28 16:54:12  autotec    dani  "
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.DataFrame(resultado)\n",
    "df.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "054f602f-d445-4edb-8d59-f3e633050d7b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
