{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "97ba0860-5624-4e52-ad93-148fe65e48ba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🧹 limpieza realizada\n",
      "✅ navegador iniciado\n",
      "📄 procesando página 1\n",
      "📄 procesando página 2\n",
      "📄 procesando página 3\n",
      "📄 procesando página 4\n",
      "📄 procesando página 5\n",
      "✅ autos extraidos: 150\n",
      "❌ error mongo: mongodb:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 5.0s, Topology Description: <TopologyDescription id: 69ee65eadce06770935c74ca, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\n",
      "\n",
      "🔍 primeros 5 resultados:\n",
      "{'marca': 'nissan', 'modelo': 'x-trail', 'año': '2023', 'kilometraje': '60300 km', 'combustible': 'bencina', 'ciudad': 'región metropolitana', 'url': 'https://www.yapo.cl/autos-usados/nissan-x-trail-2023/32024341', 'precio': 18390000, 'fecha_captura': '2026-04-26 19:21:12', 'usuario': 'dani'}\n",
      "{'marca': 'exeed', 'modelo': 'lx', 'año': '2024', 'kilometraje': '33318 km', 'combustible': 'bencina', 'ciudad': 'región metropolitana', 'url': 'https://www.yapo.cl/autos-usados/exeed-lx-2024/31740216', 'precio': 14490000, 'fecha_captura': '2026-04-26 19:21:12', 'usuario': 'dani'}\n",
      "{'marca': 'hyundai', 'modelo': 'grand i10', 'año': '2024', 'kilometraje': '20800 km', 'combustible': 'bencina', 'ciudad': 'región metropolitana', 'url': 'https://www.yapo.cl/autos-usados/hyundai-grand-i10-2024/32234911', 'precio': 9990000, 'fecha_captura': '2026-04-26 19:21:12', 'usuario': 'dani'}\n",
      "{'marca': 'chevrolet', 'modelo': 'onix', 'año': '2019', 'kilometraje': '53650 km', 'combustible': 'bencina', 'ciudad': 'región metropolitana', 'url': 'https://www.yapo.cl/autos-usados/chevrolet-onix-2019/32238139', 'precio': 7690000, 'fecha_captura': '2026-04-26 19:21:12', 'usuario': 'dani'}\n",
      "{'marca': 'citroen', 'modelo': 'c3', 'año': '2025', 'kilometraje': '41812 km', 'combustible': 'bencina', 'ciudad': 'región metropolitana', 'url': 'https://www.yapo.cl/autos-usados/citroen-c3-2025/32238140', 'precio': 7490000, 'fecha_captura': '2026-04-26 19:21:12', 'usuario': 'dani'}\n"
     ]
    }
   ],
   "source": [
    "def ejecutar_extraccion():\n",
    "\n",
    "    import os\n",
    "    import time\n",
    "    import re\n",
    "    from pymongo import MongoClient\n",
    "    from selenium import webdriver\n",
    "    from selenium.webdriver.chrome.options import Options\n",
    "    from selenium.webdriver.common.by import By\n",
    "    from selenium.webdriver.support.ui import WebDriverWait\n",
    "    from selenium.webdriver.support import expected_conditions as EC\n",
    "\n",
    "    # --- LIMPIEZA ---\n",
    "    os.system(\"pkill -9 chrome\")\n",
    "    os.system(\"pkill -9 chromedriver\")\n",
    "    os.system(\"rm -rf /tmp/.com.google.Chrome.*\")\n",
    "    os.system(\"rm -rf /tmp/.org.chromium.Chromium.*\")\n",
    "\n",
    "    print(\"🧹 limpieza realizada\")\n",
    "\n",
    "    lista_autos = []\n",
    "    driver = None\n",
    "\n",
    "    NOMBRE_GRUPO = \"autotec\"\n",
    "    USUARIO = \"dani\"\n",
    "\n",
    "    # --- NAVEGADOR ---\n",
    "    options = Options()\n",
    "    options.binary_location = \"/usr/bin/google-chrome\"\n",
    "    options.add_argument(\"--no-sandbox\")\n",
    "    options.add_argument(\"--disable-dev-shm-usage\")\n",
    "    options.add_argument(\"--disable-gpu\")\n",
    "    options.add_argument(\"--window-size=1920,1080\")\n",
    "    options.add_argument(\"--headless=new\")\n",
    "\n",
    "    try:\n",
    "        driver = webdriver.Chrome(options=options)\n",
    "        print(\"✅ navegador iniciado\")\n",
    "\n",
    "        for pagina in range(5):\n",
    "\n",
    "            url = \"https://www.yapo.cl/autos-usados\" if pagina == 0 else f\"https://www.yapo.cl/autos-usados.{pagina + 1}\"\n",
    "            driver.get(url)\n",
    "\n",
    "            print(f\"📄 procesando página {pagina + 1}\")\n",
    "            time.sleep(8)\n",
    "\n",
    "            bloques = WebDriverWait(driver, 20).until(\n",
    "                EC.presence_of_all_elements_located(\n",
    "                    (By.CSS_SELECTOR, \"a.d3-ad-tile__description\")\n",
    "                )\n",
    "            )\n",
    "\n",
    "            for bloque in bloques:\n",
    "                try:\n",
    "                    # --- nombre ---\n",
    "                    nombre = bloque.find_element(\n",
    "                        By.CSS_SELECTOR, \"span.d3-ad-tile__title\"\n",
    "                    ).text.lower().strip()\n",
    "\n",
    "                    partes = nombre.split()\n",
    "                    marca = partes[0] if len(partes) > 0 else \"\"\n",
    "                    modelo = \" \".join(partes[1:]) if len(partes) > 1 else \"\"\n",
    "\n",
    "                    # --- precio limpio ---\n",
    "                    try:\n",
    "                        precio_elemento = bloque.find_element(\n",
    "                            By.CSS_SELECTOR, \"div.d3-ad-tile__price\"\n",
    "                        )\n",
    "\n",
    "                        precio_texto = driver.execute_script(\n",
    "                            \"return arguments[0].childNodes[0].textContent;\",\n",
    "                            precio_elemento\n",
    "                        ).strip()\n",
    "\n",
    "                    except:\n",
    "                        precio_texto = \"\"\n",
    "\n",
    "                    numeros = re.findall(r\"\\d+\", precio_texto)\n",
    "                    precio = int(\"\".join(numeros)) if numeros else None\n",
    "\n",
    "                    # --- ciudad ---\n",
    "                    try:\n",
    "                        ciudad = bloque.find_element(\n",
    "                            By.CSS_SELECTOR, \"div.d3-ad-tile__location\"\n",
    "                        ).text.lower().strip()\n",
    "                    except:\n",
    "                        ciudad = \"\"\n",
    "\n",
    "                    # --- url ---\n",
    "                    url_auto = bloque.get_attribute(\"href\")\n",
    "\n",
    "                    # --- detalles ---\n",
    "                    detalles = bloque.find_elements(\n",
    "                        By.CSS_SELECTOR, \"li.d3-ad-tile__details-item\"\n",
    "                    )\n",
    "\n",
    "                    año = \"\"\n",
    "                    kilometraje = \"\"\n",
    "                    combustible = \"\"\n",
    "\n",
    "                    for d in detalles:\n",
    "                        texto = d.text.lower().strip()\n",
    "\n",
    "                        if texto.isdigit() and len(texto) == 4:\n",
    "                            año = texto\n",
    "                        elif \"km\" in texto:\n",
    "                            kilometraje = texto\n",
    "                        elif texto in [\n",
    "                            \"bencina\", \"diesel\", \"diésel\",\n",
    "                            \"hibrido\", \"híbrido\",\n",
    "                            \"electrico\", \"eléctrico\"\n",
    "                        ]:\n",
    "                            combustible = texto\n",
    "\n",
    "                    # --- GUARDAR ---\n",
    "                    lista_autos.append({\n",
    "                        \"marca\": marca,\n",
    "                        \"modelo\": modelo,\n",
    "                        \"año\": año,\n",
    "                        \"kilometraje\": kilometraje,\n",
    "                        \"combustible\": combustible,\n",
    "                        \"ciudad\": ciudad,\n",
    "                        \"url\": url_auto,\n",
    "                        \"precio\": precio,\n",
    "                        \"fecha_captura\": time.strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
    "                        \"grupo\": NOMBRE_GRUPO,\n",
    "                        \"usuario\": USUARIO\n",
    "                    })\n",
    "\n",
    "                except Exception as e:\n",
    "                    print(\"⚠️ error:\", e)\n",
    "                    continue\n",
    "\n",
    "        print(f\"✅ autos extraidos: {len(lista_autos)}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(\"❌ error selenium:\", e)\n",
    "\n",
    "    finally:\n",
    "        if driver:\n",
    "            driver.quit()\n",
    "\n",
    "    # --- MONGO LIMPIO ---\n",
    "    try:\n",
    "        client = MongoClient(\"mongodb\", 27017, serverSelectionTimeoutMS=5000)\n",
    "        db = client[\"proyecto_bigdata\"]\n",
    "        coleccion = db[\"yapoautos\"]\n",
    "\n",
    "        coleccion.delete_many({})\n",
    "\n",
    "        if lista_autos:\n",
    "            coleccion.insert_many(lista_autos)\n",
    "            print(\"✅ datos guardados en mongo\")\n",
    "        else:\n",
    "            print(\"⚠️ no hay datos\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(\"❌ error mongo:\", e)\n",
    "\n",
    "    return lista_autos\n",
    "\n",
    "\n",
    "# --- EJECUTAR ---\n",
    "resultado = ejecutar_extraccion()\n",
    "\n",
    "print(\"\\n🔍 primeros 5 resultados:\")\n",
    "for auto in resultado[:5]:\n",
    "    print(auto)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "917d1eae-4b1d-4f43-a6be-0b1ff0f968a3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>marca</th>\n",
       "      <th>modelo</th>\n",
       "      <th>año</th>\n",
       "      <th>kilometraje</th>\n",
       "      <th>combustible</th>\n",
       "      <th>ciudad</th>\n",
       "      <th>url</th>\n",
       "      <th>precio</th>\n",
       "      <th>fecha_captura</th>\n",
       "      <th>usuario</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>nissan</td>\n",
       "      <td>x-trail</td>\n",
       "      <td>2023</td>\n",
       "      <td>60300 km</td>\n",
       "      <td>bencina</td>\n",
       "      <td>región metropolitana</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/nissan-x-trai...</td>\n",
       "      <td>18390000</td>\n",
       "      <td>2026-04-26 19:21:12</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>exeed</td>\n",
       "      <td>lx</td>\n",
       "      <td>2024</td>\n",
       "      <td>33318 km</td>\n",
       "      <td>bencina</td>\n",
       "      <td>región metropolitana</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/exeed-lx-2024...</td>\n",
       "      <td>14490000</td>\n",
       "      <td>2026-04-26 19:21:12</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>hyundai</td>\n",
       "      <td>grand i10</td>\n",
       "      <td>2024</td>\n",
       "      <td>20800 km</td>\n",
       "      <td>bencina</td>\n",
       "      <td>región metropolitana</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/hyundai-grand...</td>\n",
       "      <td>9990000</td>\n",
       "      <td>2026-04-26 19:21:12</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>chevrolet</td>\n",
       "      <td>onix</td>\n",
       "      <td>2019</td>\n",
       "      <td>53650 km</td>\n",
       "      <td>bencina</td>\n",
       "      <td>región metropolitana</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/chevrolet-oni...</td>\n",
       "      <td>7690000</td>\n",
       "      <td>2026-04-26 19:21:12</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>citroen</td>\n",
       "      <td>c3</td>\n",
       "      <td>2025</td>\n",
       "      <td>41812 km</td>\n",
       "      <td>bencina</td>\n",
       "      <td>región metropolitana</td>\n",
       "      <td>https://www.yapo.cl/autos-usados/citroen-c3-20...</td>\n",
       "      <td>7490000</td>\n",
       "      <td>2026-04-26 19:21:12</td>\n",
       "      <td>dani</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       marca     modelo   año kilometraje combustible                ciudad  \\\n",
       "0     nissan    x-trail  2023    60300 km     bencina  región metropolitana   \n",
       "1      exeed         lx  2024    33318 km     bencina  región metropolitana   \n",
       "2    hyundai  grand i10  2024    20800 km     bencina  región metropolitana   \n",
       "3  chevrolet       onix  2019    53650 km     bencina  región metropolitana   \n",
       "4    citroen         c3  2025    41812 km     bencina  región metropolitana   \n",
       "\n",
       "                                                 url    precio  \\\n",
       "0  https://www.yapo.cl/autos-usados/nissan-x-trai...  18390000   \n",
       "1  https://www.yapo.cl/autos-usados/exeed-lx-2024...  14490000   \n",
       "2  https://www.yapo.cl/autos-usados/hyundai-grand...   9990000   \n",
       "3  https://www.yapo.cl/autos-usados/chevrolet-oni...   7690000   \n",
       "4  https://www.yapo.cl/autos-usados/citroen-c3-20...   7490000   \n",
       "\n",
       "         fecha_captura usuario  \n",
       "0  2026-04-26 19:21:12    dani  \n",
       "1  2026-04-26 19:21:12    dani  \n",
       "2  2026-04-26 19:21:12    dani  \n",
       "3  2026-04-26 19:21:12    dani  \n",
       "4  2026-04-26 19:21:12    dani  "
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.DataFrame(resultado)\n",
    "df.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "054f602f-d445-4edb-8d59-f3e633050d7b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
